name: DeltaCore
version: ${project.version}
main: me.bazzadev.deltacore.DeltaCore
api-version: 1.15
authors: [BazzaDEV]
commands:
  saveinv:
    description: Save inventory.
    usage: /saveinv [player]
  loadinv:
    description: Load inventory.
    usage: /loadinv [player]
  clearinv:
    description: Clear inventory.
    usage: /clearinv [player]
  staffmode:
    description: Toggles staff mode for the player.
    usage: /staffmode
  afk:
    description: Toggles AFK status.
    usage: /afk [player]
