name: DeltaCore
version: ${project.version}
main: me.bazzadev.deltacore.DeltaCore
api-version: 1.15
authors: [BazzaDEV]
depend: [Vault, NametagEdit]
commands:
  portalhelper:
    description: Calculates the correct coordinates for nether placement.
    usage: /portalhelper
  search:
    description: Search nearby containers for a specified item.
    usage: /search <item name>

  heal:
    description: Heals the player.
    usage: /heal [player]
  feed:
    description: Feed the player.
    usage: /feed [player]
  coords:
    description: Puts the player's coordinates in chat.
    usage: /coords

  tp:
    description: Teleports the player.
    usage: /tp

  saveinv:
    description: Save inventory.
    usage: /saveinv [player]
    aliases: [saveinventory]
  loadinv:
    description: Load inventory.
    usage: /loadinv [player]
    aliases: [loadinventory]
  clearinv:
    description: Clear inventory.
    usage: /clearinv [player]
    aliases: [clearinventory]
  restoreinv:
    description: Restores your inventory to its contents before a certain event.
    usage: /restoreinv <fromdeath | other> <player>

  staffmode:
    description: Toggles staff mode for the player.
    usage: /staffmode

  afk:
    description: Toggles AFK status.
    usage: /afk [player]
  fly:
    description: Gives you levitation powers.
    usage: /fly [player]
  vanish:
    description: Toggles the player's visibility on the server.
    usage: /vanish [player]
    aliases: [v]

  gms:
    description: Sets the player's gamemode to survival.
    usage: /gms [player]
  gma:
    description: Sets the player's gamemode to adventure.
    usage: /gma [player]
  gmc:
    description: Sets the player's gamemode to creative.
    usage: /gmc [player]
  gmspec:
    description: Sets the player's gamemode to spectator.
    usage: /gmspec [player]