name: DeltaCore
version: ${project.version}
main: dev.bazza.deltacore.DeltaCore
api-version: 1.16
authors: [ BazzaDEV ]
description: A lightweight Paper plugin for survival multiplayer server.
website: bazza.dev