name: DeltaCore
version: ${project.version}
main: dev.bazza.deltacore.DeltaCore
api-version: 1.16
authors: [ BazzaDEV ]
website: bazza.dev
commands:
  afk:
    description: Toggles the player's AFK status.
    usage: /afk
